@url = https://supernatural-spooky-apparition-4rg4prr775r37wj6-8080.app.github.dev/

###
GET {{url}}/categorias

###
GET {{url}}/categorias/10

###
POST {{url}}/categorias
Content-Type: application/json

{
    "nome": "Conhecimentos Gerais"
}

###
DELETE {{url}}/categorias/5

###
PUT {{url}}/categorias/10
Content-Type: application/json

{
    "nome": "Arquitetura de APIs  - Alterado"
}