@url = https://8080-giogiuseppe-apiquiz2024-l5cpr0541pc.ws-us116.gitpod.io

###
GET {{url}}/categorias

###
POST {{url}}/categorias
Content-Type: application/json

{
    "nome": "Arquitetura de APIs 1"
}