@url = https://psychic-doodle-r74xxqxg4v25vv5-8080.app.github.dev

GET {{url}}/questoes

###
POST {{url}}/questoes
Content-Type: application/json

{
    "enunciado": "Questão com Categoria Novo Tese",
    "categoria" : {
        "id": 8
    }
}

###
PUT {{url}}/questoes/4
Content-Type: application/json

{
    "enunciado": "Questão com Categoria Novo Tese - Alterada",
    "categoria" : {
        "id": 4
    }
}

###
DELETE {{url}}/questoes/1